services:
  backend:
    image: node:18
    command: bash -c "npm install && npm run start:dev"
    working_dir: /app
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - 3000:3000
    user: 1000:1000
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: pass
      DB: sklep
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3000
      GOOGLE_SECRET: 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
      GOOGLE_ID: 777794280584-9ofa3ul724h1oku3sqv2fc0rmn9k9jql.apps.googleusercontent.com
      SECRET_KEY: abecadlo
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sklep

volumes:
  db-data:
